[package]
name = "vsvg-viewer"
description = "Rust prototype for vpype-viewer V2."
authors = ["Antoine Beyeler"]
version = "0.1.0-alpha.0"
edition = "2021"



[dependencies]
vsvg-core = { path = "../vsvg-core" }
kurbo = "0.9.1"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench_triangulation"
harness = false
